WebAssemblySummit/webassembly-summit.org

- README.md
> [WIP] feat(readme): add README with status badge, brief desc

- README.md
closes #2 
Added some contributing instructions, to pitch a new idea, and then how to develop with the project! 😄
> Added some contributing docs

- pages/index.tsx
closes #6 
Adds the contact email per the design in #6 😄
> Added Contact Us Information

- pages/_app.tsx
- pages/_document.tsx
- pages/index.tsx
> Fix accessibility issues

- pages/index.tsx
> fix(contact): show email address in page

- CODE_OF_CONDUCT.md
- pages/index.tsx
> feat(coc): add CODE_OF_CONDUCT.md

- pages/index.tsx
> feat(footer): add hashtag

- pages/index.tsx
> Added the application deadline to the website

- pages/index.tsx
> fix(address): street number first

- pages/index.tsx
> feat(cta): registration is closed

- pages/about.tsx
addresses part of #43: adds the FAQ items about tickets and attendance costs to the about page (see question on Discord #summit channel)
> update ticket faq

- components/NavBar.tsx
- pages/about/index.tsx
- pages/speakers/index.tsx
Simplified and automated active route detection in the navbar. There is no need anymore to pass the currentPage prop manually as before (was `<NavBar currentPage="About">`).
> simplified navbar active page detection

- components/NavBar.tsx
addresses the most recent lighthouse report - similar fix to #69
> lighthouse referrer security problem fix

- components/NavBar.tsx
fixed: discord link was incorrect (linked to a twitter redirect)
> fixed discord link

- pages/_app.tsx
- fix for ipad pro splash screen (was skewed, this should fix this)
- status bar color translucent
> fixes for pwa ui glitches

- components/NavBar.tsx
- pages/index.tsx
Fixes #64 
- better centering, scaling and column layout of the logo on the landing page
- screenshots of old state see #64
> landing page layout refinements

- hooks/useScrollDirection.ts
- pages/_app.tsx
- pages/about/index.tsx
- pages/index.tsx
-  landing page better centered and one page #81, #64
- about page column layout slightly wider #30 
- less sensitive scroll direction change #54 
- shortcut icon fix #41
> landing page + about page column layout fixes

- data/about.tsx
adds link to youtube channel to about page #108
> added youtube links

- data/about.tsx
The other peoplee on this list have done fantastic work, and put a lot of energy into making the Summit real. I unfortunately haven't been able to spend nearly as much time and energy on it, so I feel that having me on this list isn't a fair representation.
> Remove myself from organizers list

- pages/index.tsx
- added a bottom margin top prevent the navbar ending on top of the livestream button
- minor refinements to landing page layout
> fix for landing page layout scrolling

- data/about.tsx
- pages/index.tsx
> Add link to photo album

- data/talks.tsx
- pages/speakers/[id].tsx
> Embed videos for individual talks

- src/faq.md
> Created a FAQ based on the CFP and Old FAQ

- _data/meta.js
> Fix link to Twitter

- src/schedule.md
I went through the Email with Argus, and implemented the timetable you laid out / we chatted about! :smile: 
I have two things I'd like to point out:
* I gave us time to do some intros, explain the CoC and things in the beginning, and general good byes at the end. 
* Nick Fitzgerald mentioned to me that they're talk is shorted, so I purposely made it only a 20 minute timeslot :smile: 
* I added some emojis to all the MC times, because they looked cool :joy: 
Let me know what you think! :smile:
> Added times to the schedule page
